name: CI Test


on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Start application
        working-directory: backend
        run: |
          node server.js &
          sleep 3

      - name: Health check
        run: curl --fail http://localhost:3000/health

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::066036524900:role/WardrobeGitHubActionsRole
          aws-region: ap-northeast-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Generate temporary SSH key
        run: |
          ssh-keygen -t ed25519 -f /tmp/wardrobe_key -N ""
      
      - name: Copy artifact to EC2-A
        run: |
          scp \
            -i /tmp/wardrobe_key \
            -o StrictHostKeyChecking=no \
            -o ProxyCommand="aws ec2-instance-connect open-tunnel --instance-id i-09f328a19c5fdbfac --instance-connect-endpoint-id eice-0552b70076fcf78b9" \
            /tmp/wardrobe-backend.tar.gz \
            ubuntu@i-YOUR_EC2_A_ID:/home/ubuntu/wardrobe-backend.tar.gz

      - name: Send temporary SSH public key
        run: |
          aws ec2-instance-connect send-ssh-public-key \
            --instance-id i-09f328a19c5fdbfac \
            --instance-os-user ubuntu \
            --ssh-public-key file:///tmp/wardrobe_key.pub \
            --region ap-northeast-2

      - name: Test SSH through EICE
        run: |
          ssh \
            -i /tmp/wardrobe_key \
            -o StrictHostKeyChecking=no \
            -o ProxyCommand="aws ec2-instance-connect open-tunnel --instance-id i-09f328a19c5fdbfac --instance-connect-endpoint-id eice-0552b70076fcf78b9" \
            ubuntu@i-09f328a19c5fdbfac \
            "hostname && whoami"

      - name: Create deployment artifact
        working-directory: backend
        run: |
          tar \
            --exclude='.env' \
            --exclude='*.log' \
            -czf /tmp/wardrobe-backend.tar.gz .
          
          ls -lh /tmp/wardrobe-backend.tar.gz