name: CI Test

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Show environment
        run: |
          echo "GitHub Actions is running"
          pwd
          ls -la
          node -v
          npm -v